markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Parth Chadha
url: http://parthchadha.wordpress.com
description: A fantastic blog that is fantastic.
twitter: parth_29
