#markdown: redcarpet
highlighter: pygments
#permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Parth Chadha
url: http://parthchadha.github.io
description: What if human brain is hackable?
twitter: parth_29

