markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Parth Chadha
url: http://parthchadha.wordpress.com
description: What if human brain is hackable?
twitter: parth_29
