title: Parth Chadha
#markdown:    kramdown
highlighter: pygments
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: gfm
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Parth Chadha
url: http://parthchadha.github.io
description: What if human brain is hackable?
twitter: parth_29

#google_analytics: UA-153481261-1
